site:
  title: Antora Demo Page
  start_page: github-antora-demo:ROOT:index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs

antora:
  extensions:
    - require: '@antora/lunr-extension'
      languages: [en, de]

ui:
  bundle:
    url: _antora/ui-bundle.zip
    snapshot: true
  supplemental_files: _antora/supplemental_ui
  output_dir: antora

output:
  clean: true

runtime:
  log:
    level: debug